JLA-0.2.2.4
kazuさん方式から自分の方式を混ぜた。
あとコードを見なおした。
Spigot-1.9.2
実行すると以下のエラーが出る。
[時刻 ERROR]: Could not load 'plugins\JoinLeaveAction-0.2.2.4.jar' in
folder
'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException
at
org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.ja
va:135) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-048849c]
at
org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.j
ava:329) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-048849c]
at
org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.
java:251) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-048849c]
at
org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.jav
a:296) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-048849c]
at
net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java
:201) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-048849c]
at
net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:
527) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-048849c]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
at com.github.smk7758.jla.ConsoleLog.<init>(ConsoleLog.java:19) ~[?:?]
at com.github.smk7758.jla.Main.<init>(Main.java:26) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
~[?:1.8.0_92]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
~[?:1.8.0_92]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown
Sour
ce) ~[?:1.8.0_92]
at java.lang.reflect.Constructor.newInstance(Unknown Source)
~[?:1.8.0_92
]
at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_92]
at
org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java
:76) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-048849c]
at
org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.ja
va:131) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-048849c]
... 6 more